[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'virtualenv /app/venv',
  '/app/venv/bin/pip install -r backend/requirements.txt'
]

[phases.build]
cmds = ['chmod +x backend/start.sh']

[start]
cmd = "cd backend && ./start.sh"
